[keyboard]
name = "Luciano KB"
product_name = "Luciano Custom Keyboard"
vendor_id = 0xFEED
product_id = 0x0001
manufacturer = "Luciano"
chip = "stm32f103c8"

[matrix]
row_pins = ["PA0", "PA1", "PA2", "PA4", "PA5", "PA6", "PA7", "PA8", "PA9", "PB0", "PB1", "PB10", "PB11", "PB12", "PB13", "PB14", "PB15"]
col_pins = ["PA10", "PB3", "PB4", "PB5", "PB6", "PB7", "PB8", "PB9"]
row2col = false 

[layout]
rows = 17
cols = 8
layers = 2
keymap = [
    [
        # PA0
        ["Up", "Left", "_", "_", "_", "End", "Home", "_"],
        # PA1
        ["_", "Down", "_", "_", "_", "F11", "Delete", "_"],
        # PA2
        ["_", "Right", "_", "_", "_", "F12", "PrintScreen", "_"],
        # PA4
        ["_", "_", "Dot", "L", "O", "Kb9", "F8", "F7"],
        # PA5
        ["Grave", "Semicolon", "RightBracket", "Semicolon", "P", "Kb0", "Minus", "Grave"],
        # PA6
        ["F6", "Slash", "Comma", "K", "I", "Kb8", "Equal", "LeftBracket"],
        # PA7
        ["H", "N", "M", "J", "U", "Kb7", "Kb6", "Y"],
        # PA8
        ["_", "_", "_", "PageDown", "PageUp", "LGui", "_", "_"],
        # PA9
        ["_", "_", "_", "MO(1)", "_", "_", "_", "Application"],
        # PB0
        ["F5", "Space", "Enter", "_", "_", "F10", "F9", "Backspace"],
        # PB1
        ["G", "B", "V", "F", "R", "Kb4", "Kb5", "T"],
        # PB10
        ["F4", "_", "C", "D", "E", "Kb3", "F2", "F3"],
        # PB11
        ["Backslash", "_", "X", "S", "W", "Kb2", "F1", "CapsLock"],
        # PB12
        ["Escape", "AudioMute", "Z", "A", "Q", "Kb1", "Quote", "Tab"],
        # PB13
        ["LAlt", "RAlt", "_", "_", "_", "Insert", "_", "_"],
        # PB14
        ["_", "_", "RShift", "_", "_", "_", "_", "LShift"],
        # PB15
        ["_", "_", "_", "_", "_", "_", "LCtrl", "_"]
    ],
    [
        # Camada 1 (Vazia)
        ["_", "_", "_", "_", "_", "_", "_", "_"], ["_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_"], ["_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_"], ["_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_"], ["_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_"], ["_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_"], ["_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_"], ["_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_"], ["_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_"]
    ]
]
